version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ulem_tracker
    ports:
      - "5477:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: